/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CurriculoController;
import Model.Curriculo;
import Model.Usuario;

/**
 *
 * @author CristianSSD
 */
public class MainWindow extends javax.swing.JFrame {

    private Usuario usuario;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }
    
    public void AbrirCadastroCurriculo(){
        Curriculo curriculo = CurriculoController.GetInstance().GetCurriculo(usuario);
    }
    
    public void CarregarCurriculo(){
        Curriculo curriculo = CurriculoController.GetInstance().GetCurriculo(usuario);
    }
    
    public void ExluirCurriculo(){
        CurriculoController.GetInstance().DeletarCurriculo(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SairJMI = new javax.swing.JMenuItem();
        CurriculoJM = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        Atualizar = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("File");

        SairJMI.setText("Sair");
        jMenu1.add(SairJMI);

        jMenuBar1.add(jMenu1);

        CurriculoJM.setText("Curriculo");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Cadastrar);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Consultar);

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Atualizar);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        CurriculoJM.add(Excluir);

        jMenuBar1.add(CurriculoJM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CadastroCurriculo(usuario.getUserName()).setVisible(true);
                }
            });        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        ExluirCurriculo();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        AbrirCadastroCurriculo();        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        CarregarCurriculo();
    }//GEN-LAST:event_AtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atualizar;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenu CurriculoJM;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem SairJMI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
