/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CurriculoController;
import Model.Curriculo;
import Model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MainWindow extends javax.swing.JFrame {

    private static Usuario usuario;
    private static MainWindow instance;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static MainWindow GetInstance(){
        if(instance == null){
            instance = new MainWindow(usuario);
        }
        return instance;
    }
    
    public void AbrirCadastroCurriculo(){
        JPanel curriculoPanel = new CurriculoJPanel(usuario.getUserName(),null,true);
        MainPanel.add(curriculoPanel);
        curriculoPanel.setVisible(true);
    }
    
    public void CarregarCurriculo(){
        Curriculo curriculo = CurriculoController.GetInstance().GetCurriculo(usuario);
        JPanel curriculoPanel = new CurriculoJPanel(usuario.getUserName(),curriculo,false);
        MainPanel.add(curriculoPanel);
        curriculoPanel.setVisible(true);
    }
    
    public void AtualizarCurriculo(){
        Curriculo curriculo = CurriculoController.GetInstance().GetCurriculo(usuario);
        JPanel curriculoPanel = new CurriculoJPanel(usuario.getUserName(),curriculo,true);
        MainPanel.add(curriculoPanel);
        curriculoPanel.setVisible(true);
    }
    
    public void ExluirCurriculo(){
        CurriculoController.GetInstance().DeletarCurriculo(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SairJMI = new javax.swing.JMenuItem();
        CurriculoJM = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        Atualizar = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("File");

        SairJMI.setText("Sair");
        SairJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairJMIActionPerformed(evt);
            }
        });
        jMenu1.add(SairJMI);

        jMenuBar1.add(jMenu1);

        CurriculoJM.setText("Curriculo");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Cadastrar);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Consultar);

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        CurriculoJM.add(Atualizar);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        CurriculoJM.add(Excluir);

        jMenuBar1.add(CurriculoJM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(814, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        if(CurriculoController.GetInstance().HasCurriculoCadastrado(usuario)){
            JOptionPane.showMessageDialog(this, "Já existe um curriculo cadastrado para este usuário");
        }else{
            AbrirCadastroCurriculo();// TODO add your handling code here:    
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        ExluirCurriculo();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        CarregarCurriculo();        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        AtualizarCurriculo();
    }//GEN-LAST:event_AtualizarActionPerformed

    private void SairJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairJMIActionPerformed
        System.exit(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_SairJMIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atualizar;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenu CurriculoJM;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem SairJMI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
